export const
  
  /** USER **/
  SET_USER = 'SET_USER',
  CLEAR_USER = 'CLEAR_USER',
  USER_LOADING = 'USER_LOADING',
  
  /** CATEGORIES **/
  SET_CATEGORIES = 'SET_CATEGORIES',
  CLEAR_CATEGORIES = 'CLEAR_CATEGORIES',
  CATEGORIES_LOADING = 'CATEGORIES_LOADING',

  /** PRODUCTS **/
  SET_PRODUCTS = 'SET_PRODUCTS',
  CLEAR_PRODUCTS = 'CLEAR_PRODUCTS',
  PRODUCTS_LOADING = 'PRODUCTS_LOADING',
  
  /** CART **/
  ADD_PRODUCT = 'ADD_PRODUCT',
  REMOVE_PRODUCT = 'REMOVE_PRODUCT',
  CHANGE_COUNTER = 'CHANGE_COUNTER',
  SET_ORDERS = 'SET_ORDERS',
  CART_LOADING = 'CART_LOADING',
  CLEAR_CART = 'CLEAR_CART',
  CLEAR_ORDERS = 'CLEAR_ORDERS',
  
  /** B **/
  B = 'B';
